## auth/login
### POST /api/auth/login
POST http://localhost:3000/api/auth/login
content-type: application/json

{"username": "JohnDoe", "password": "to-be-hashed-pw1"}

### GET my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MDExODU2MzZ9.-7WqAwvCeEdyOmmtLC5QtDcxo_stVhy7H1vdVV0tBMc
# Media sharing api http test requests

## /api/media endpoit

### Get all media
GET http://localhost:3000/api/media

### Get media by id
GET http://localhost:3000/api/media/14

### Get media by id FAIL
GET http://localhost:3000/api/media/959099

### Post media
POST http://localhost:3000/api/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MDExODU2MzZ9.-7WqAwvCeEdyOmmtLC5QtDcxo_stVhy7H1vdVV0tBMc
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

tacos
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user_id"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="image.jpg"
Content-Type: image/jpeg

/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Post media (invalid file)
POST http://localhost:3000/api/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MDExODU2MzZ9.-7WqAwvCeEdyOmmtLC5QtDcxo_stVhy7H1vdVV0tBMc
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

New media title k
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file.pdf"
Content-Type: application/pdf

< ./tacos_bg.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Post media FAIL
POST http://localhost:3000/api/media
content-type: application/json

{"msg": "HEllo"}

### Update media
PUT http://localhost:3000/api/media/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MDExODU2MzZ9.-7WqAwvCeEdyOmmtLC5QtDcxo_stVhy7H1vdVV0tBMc
content-type: application/json

{
  "filename": "updatedAdmin.jpg",
  "title": "Updated Media",
  "description": "updated description"
}
### Update media FAIL
PUT http://localhost:3000/api/media/260
content-type: application/json

{
  "something": "this will fail",
}

### Delete media
DELETE http://localhost:3000/api/media/9590

## /api/users endpoint

### Get all users
GET http://localhost:3000/api/users

### Get user by id
GET http://localhost:3000/api/users/32

### Get user by id FAIL
GET http://localhost:3000/api/users/959099

### Post users 
POST http://localhost:3000/api/users
content-type: application/json

{
  "username": "newUser",
  "password": "newpassword",
  "email": "newuser@example.com"
}

### Update user
PUT http://localhost:3000/api/users/27
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MDExODU2MzZ9.-7WqAwvCeEdyOmmtLC5QtDcxo_stVhy7H1vdVV0tBMc
content-type: application/json

{
  "username": "JohnDoe3",
  "password": "newpassword",
  "email": "johndoe@example.com"
}

### Update users FAIL
PUT http://localhost:3000/api/users/340
content-type: application/json

{
  "something": "this will fail"
}

### Delete users
DELETE http://localhost:3000/api/users/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MDExODU2MzZ9.-7WqAwvCeEdyOmmtLC5QtDcxo_stVhy7H1vdVV0tBMc

## /api/comments endpoint

### Get comments by media id
GET http://localhost:3000/api/comments/media/13

### Get comments by user id
GET http://localhost:3000/api/comments/user/10

### Post a comment

POST http://localhost:3000/api/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNSwidXNlcm5hbWUiOiJBbm9uNTQ2OCIsImVtYWlsIjoiYW5vbjU0NjhAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MDExNzE5NzR9.OaryRK9Dq6YWry3_cHVVmi3ujWz5easQUw6DVZjiKok
Content-Type: application/json

{
    "media_id": 19,
    "comment_text": "Nice pic!"
}

### Post a comment FAIL

POST http://localhost:3000/api/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyNywidXNlcm5hbWUiOiJKb2huRG9lIiwiZW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiaWF0IjoxNzAxMTY1MzA2fQ.4v0AflcPscBdHxYr-2qIeNLY1xJw1HAt6wmB18RnxSs
Content-Type: application/json

{
    "field": 15
}

### Update a comment

PUT http://localhost:3000/api/comments/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyNywidXNlcm5hbWUiOiJKb2huRG9lMiIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbSIsInVzZXJfbGV2ZWxfaWQiOjIsImlhdCI6MTcwMTE4MzcwNX0.yPXV_aPGVZDrQKD0jhabiwtfKuaKB-C9zgoXx4K8VX4
Content-Type: application/json

{
    "comment_text": "There is a new comment here"
}

### Delete a comment

DELETE http://localhost:3000/api/comments/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyOCwidXNlcm5hbWUiOiJCb2IiLCJlbWFpbCI6ImJvYkBleGFtcGxlLmNvbSIsInVzZXJfbGV2ZWxfaWQiOjEsImlhdCI6MTcwMTE3NTIxOH0.APN20-VLS5W4iQFvV8G_PiTLwUSfp4pX_T_wUusk_r0