### GET /
GET http://localhost:3000/

### GET /items
GET http://localhost:3000/items

### GET /items/:id
GET http://localhost:3000/items/20

### POST /items
POST http://localhost:3000/items
content-type: application/json

{"name": "kurkku"}

### POST /items error
POST http://localhost:3000/items

{"jotain": "jotan"}

### PUT /items/:id
PUT http://localhost:3000/items/20
content-type: application/json

{"name": "kurkut"}

### DELETE /items/:id
DELETE http://localhost:3000/items/20




### GET /todos
GET http://localhost:3000/todos

### GET /todos/:id
GET http://localhost:3000/todos/2

### POST /todos
POST http://localhost:3000/todos
content-type: application/json

{"task": "Make the API public", "completed": false }

### PUT /todos/:id
PUT http://localhost:3000/todos/3
content-type: application/json

{"task": "Make the API public", "completed": true }

### DELETE /todos/:id
DELETE http://localhost:3000/todos/3